package garden

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/nichsedge/ierp/internal/decisions"
	"github.com/nichsedge/ierp/internal/gadgets"
	"github.com/nichsedge/ierp/internal/projects"
	"github.com/nichsedge/ierp/internal/reviews"
)

// ResolveGardenRoot determines the target Digital Garden content directory.
func ResolveGardenRoot(customPath string) string {
	if customPath != "" {
		if abs, err := filepath.Abs(customPath); err == nil {
			return abs
		}
		return customPath
	}

	if env := os.Getenv("GARDEN_CONTENT"); env != "" {
		if abs, err := filepath.Abs(env); err == nil {
			return abs
		}
		return env
	}

	home, err := os.UserHomeDir()
	if err == nil {
		candidates := []string{
			filepath.Join(home, "Projects", "digital-graveyard", "content"),
			filepath.Join(home, "Projects", "digital-garden", "content"),
		}
		for _, c := range candidates {
			if fi, err := os.Stat(c); err == nil && fi.IsDir() {
				return c
			}
		}
		return filepath.Join(home, "Projects", "digital-graveyard", "content")
	}

	return "content"
}

var nonAlphanumericSlug = regexp.MustCompile(`[^\w\s-]`)
var spacesSlug = regexp.MustCompile(`[\s_-]+`)

// Slugify generates a filesystem-safe slug.
func Slugify(text string) string {
	cleaned := strings.ToLower(strings.TrimSpace(text))
	cleaned = nonAlphanumericSlug.ReplaceAllString(cleaned, "")
	cleaned = spacesSlug.ReplaceAllString(cleaned, "-")
	cleaned = strings.Trim(cleaned, "-")
	if cleaned == "" {
		return "untitled"
	}
	return cleaned
}

// ExportSummary contains counts of exported notes.
type ExportSummary struct {
	Projects       int `json:"projects"`
	Decisions      int `json:"decisions"`
	Retrospectives int `json:"retrospectives"`
	Gadgets        int `json:"gadgets"`
}

// ExportAll writes projects, decisions, reviews, and gadgets to the Digital Garden.
func ExportAll(database *sql.DB, gardenRoot string) (*ExportSummary, error) {
	root := ResolveGardenRoot(gardenRoot)
	summary := &ExportSummary{}

	// 1. Projects
	pCount, err := ExportProjects(database, root)
	if err != nil {
		return nil, fmt.Errorf("failed exporting projects: %w", err)
	}
	summary.Projects = pCount

	// 2. Decisions (PDRs)
	dCount, err := ExportDecisions(database, root)
	if err != nil {
		return nil, fmt.Errorf("failed exporting decisions: %w", err)
	}
	summary.Decisions = dCount

	// 3. Retrospectives
	rCount, err := ExportRetrospectives(database, root)
	if err != nil {
		return nil, fmt.Errorf("failed exporting retrospectives: %w", err)
	}
	summary.Retrospectives = rCount

	// 4. Gadgets
	gCount, err := ExportGadgets(database, root)
	if err != nil {
		return nil, fmt.Errorf("failed exporting gadgets: %w", err)
	}
	summary.Gadgets = gCount

	return summary, nil
}

// ExportProjects generates markdown files in content/Knowledge/Projects/
func ExportProjects(database *sql.DB, gardenRoot string) (int, error) {
	dir := filepath.Join(gardenRoot, "Knowledge", "Projects")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return 0, err
	}

	projs, err := projects.ListProjects(database, "all")
	if err != nil {
		return 0, err
	}

	for _, p := range projs {
		filename := fmt.Sprintf("%s.md", p.Slug)
		filePath := filepath.Join(dir, filename)

		content := fmt.Sprintf(`---
title: "%s"
date: %s
tags: [project, strategic-initiative]
publish_external: true
status: "%s"
priority: "%s"
target_date: "%s"
---

# %s

> Strategic initiative tracked in iERP.

**Status**: %s | **Priority**: %s  
**Timeline**: %s → %s

## Description
%s

---
*Generated by iERP Digital Garden Sync engine.*
`, p.Title, p.CreatedAt[:10], p.Status, p.Priority, p.TargetDate,
			p.Title, p.Status, p.Priority, p.StartDate, p.TargetDate, p.Description)

		if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
			return 0, err
		}
	}

	return len(projs), nil
}

// ExportDecisions generates markdown notes in content/Knowledge/Decisions/
func ExportDecisions(database *sql.DB, gardenRoot string) (int, error) {
	dir := filepath.Join(gardenRoot, "Knowledge", "Decisions")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return 0, err
	}

	list, err := decisions.ListDecisions(database, "all", nil)
	if err != nil {
		return 0, err
	}

	for _, d := range list {
		filename := fmt.Sprintf("PDR - %s.md", Slugify(d.Title))
		filePath := filepath.Join(dir, filename)

		content := fmt.Sprintf(`---
title: "PDR: %s"
date: %s
tags: [decision, pdr]
publish_external: true
status: "%s"
confidence: %d
review_date: "%s"
---

# Decision: %s

**Choice**: %s  
**Confidence Score**: %d / 10  
**Scheduled Review**: %s  
**Status**: %s

## Context & Problem
%s

## Expected Outcome
%s

## Retrospective Calibration
%s

---
*Logged in iERP Decision Journal.*
`, d.Title, d.CreatedAt[:10], d.Status, d.Confidence, d.ReviewDate,
			d.Title, d.Choice, d.Confidence, d.ReviewDate, d.Status,
			d.Context, d.ExpectedOutcome, d.ActualOutcome)

		if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
			return 0, err
		}
	}

	return len(list), nil
}

// ExportRetrospectives generates notes in content/Write/Retrospectives/
func ExportRetrospectives(database *sql.DB, gardenRoot string) (int, error) {
	dir := filepath.Join(gardenRoot, "Write", "Retrospectives")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return 0, err
	}

	list, err := reviews.ListRetrospectives(database, "all", 100)
	if err != nil {
		return 0, err
	}

	for _, r := range list {
		filename := fmt.Sprintf("%s - %s.md", strings.Title(r.PeriodType), r.PeriodStart)
		filePath := filepath.Join(dir, filename)

		content := fmt.Sprintf(`---
title: "%s Retrospective: %s"
date: %s
tags: [retrospective, double-loop-learning]
publish_external: true
period_type: "%s"
rating: %d
---

# %s Retrospective (%s → %s)

**Overall Rating**: %d / 10

## 🎯 Wins & Energy Creators
%s

## ⚡ Energy Drains & Friction
%s

## 💡 Lessons Learned
%s

## 🚀 Focus for Next Cycle
%s

---
*Exported by iERP Double-Loop Learning Engine.*
`, strings.Title(r.PeriodType), r.PeriodStart, r.PeriodStart, r.PeriodType, r.Rating,
			strings.Title(r.PeriodType), r.PeriodStart, r.PeriodEnd, r.Rating,
			r.Wins, r.DrainsBurnout, r.Lessons, r.FocusNext)

		if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
			return 0, err
		}
	}

	return len(list), nil
}

// ExportGadgets generates notes in content/Knowledge/Entities/Gadget/
func ExportGadgets(database *sql.DB, gardenRoot string) (int, error) {
	dir := filepath.Join(gardenRoot, "Knowledge", "Entities", "Gadget")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return 0, err
	}

	list, err := gadgets.ListGadgets(database, "", "all")
	if err != nil {
		return 0, err
	}

	count := 0
	for _, g := range list {
		if !g.IsPublic {
			continue
		}
		filename := fmt.Sprintf("%s.md", Slugify(g.Name))
		filePath := filepath.Join(dir, filename)

		content := fmt.Sprintf(`---
title: "%s"
date: %s
tags: [gadget, hardware, entity]
publish_external: true
category: "%s"
brand: "%s"
status: "%s"
---

# %s

**Brand**: %s | **Category**: %s  
**Status**: %s | **Purchased**: %s

## Notes & Specs
%s

---
*Exported by iERP Gadget Registry.*
`, g.Name, g.CreatedAt[:10], g.Category, g.Brand, g.Status,
			g.Name, g.Brand, g.Category, g.Status, g.PurchaseDate, g.Notes)

		if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
			return 0, err
		}
		count++
	}

	return count, nil
}
